### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by karlskewes** [karlskewes/spinnaker-kustomize#2]
# TODO

- [ ] gate basic authentication
- [x] keel crashes on startup, orca config - ReplicaSet set to 0 for now
- [x] clouddriver manage cluster deployed to - ServiceAccount, ~ClusterRole~, ClusterRoleBinding
- [ ] mariadb password supply via env var to kustomize?
- [x] clouddriver kubernetes provider config? - Refer docs
- [x] clouddriver aws provider config? - Refer docs
- [ ] armory observability plugin? - Refer docs, but should set plugin root dir in `spinnaker.yml`
- [ ] deck `securityContext`?
- [ ] use what useful from old docs
- [ ] enable kayenta in `spinnaker.yml`?

#### Set the Spinnaker version

By default, this base kustomization deploys the `master-latest-validated`
version of each microservice, which is most recent version that has passed our
integration tests. To deploy a different version, you'll need to override the
version of each microservice in the `images` block in the `kustomization.yml`
file.

To deploy a specific version of Spinnaker, override each image's tag with
`spinnaker-{version-number}`. For example, to deploy Spinnaker 1.21.0, override
the tag for each microservice to be `spinnaker-1.21.0`:

```yaml
images:
  - name: us-docker.pkg.dev/spinnaker-community/docker/clouddriver
    newTag: spinnaker-1.21.0
  - name: us-docker.pkg.dev/spinnaker-community/docker/deck
    newTag: spinnaker-1.21.0
# ...
```

#### (Optional) Use a specific version of kustomization

With a reference of the version, you can use a specific version with conviction, after examining if the version works well with your configurations. Without a reference, a resource link always references `master`. You can check out the available versions [here](https://github.com/spinnaker/kustomization-base/releases).

For example:

```yaml
resources:
  - github.com/spinnaker/kustomization-base/core?ref=v0.1.0
```

For further details, see the [documentation](https://kubectl.docs.kubernetes.io/references/kustomize/resource/) for the `resources` field.

**Comment by karlskewes** [comment]
Moved to linked project https://github.com/users/karlskewes/projects/1/views/1
